### ISSUE TITLE
Genesis configuration

### ISSUE THREAD

**Issue by ineiti** [dedis/student_18_omniledger#18]
We need a way to store the following information (feel free to edit and add/remove) in the genesis block:

- genesis-darc that defines who is allowed to work on this omniledger. Some example of policies

**Comment by kc1212** [comment]
The minimum set of rules would be
- "_evolve": usually this needs to have multiple signers and only accept it if a threshold number of signatures are present. For testing or simple deployment, one signer is enough.
- "add_darc": this is a omniledger specific rules and it allows nodes to add new darcs or evolve existing darcs, if the signatures are correct. Spamming/DoS might be an issue if a malicious node has the "add_darc" permission, it will add a lot of rubbish darcs. The "genesis-signers" should come together and revoke the permission of the malicious node if this attack should happen.

The "sign" rule is not essential because it's unlikely that a non-genesis darc will delegate something to the genesis darc. But it can always be added at a later stage if necessary.

**Comment by kc1212** [comment]
Questions:
- Should we use one genesis-darc per skipchain, or one global genesis-darc?
- What addition information should we store in the genesis-darc, block interval? Where do we store these information?
- etc.

**Comment by kc1212** [comment]
Closed by #49 and #53
